"""
Suggestion Model

Stores improvement suggestions generated by design analysis.

Converted from Prisma schema:
- Three enums: Category, Severity, Status
- Includes trigger_keywords as PostgreSQL ARRAY type
- Status tracking for addressed/ignored suggestions
"""

import enum
from datetime import datetime, timezone
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import (
    String,
    Text,
    Integer,
    DateTime,
    ForeignKey,
    Enum as SAEnum,
    ARRAY,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.project import Project


class SuggestionCategory(str, enum.Enum):
    """Categories for suggestions based on system design areas."""
    CACHING = "CACHING"
    SCALABILITY = "SCALABILITY"
    SECURITY = "SECURITY"
    RELIABILITY = "RELIABILITY"
    PERFORMANCE = "PERFORMANCE"
    DATABASE = "DATABASE"
    API_DESIGN = "API_DESIGN"
    GENERAL = "GENERAL"


class SuggestionSeverity(str, enum.Enum):
    """Severity levels for suggestions."""
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class SuggestionStatus(str, enum.Enum):
    """Status of a suggestion."""
    OPEN = "OPEN"
    ADDRESSED = "ADDRESSED"
    IGNORED = "IGNORED"


class Suggestion(Base):
    """
    Suggestion model for AI-generated improvement recommendations.
    
    Attributes:
        id: Primary key
        title: Short title for the suggestion
        description: Detailed explanation
        category: Type of suggestion (caching, security, etc.)
        severity: Importance level (info, warning, critical)
        design_version: Which version of design triggered this
        project_id: Foreign key to project
        status: Whether addressed, ignored, or open
        addressed_at: When the suggestion was addressed
        addressed_in_version: Which version addressed it
        trigger_keywords: Keywords that triggered this suggestion
        created_at: When suggestion was created
    """
    
    __tablename__ = "suggestions"
    
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    
    category: Mapped[SuggestionCategory] = mapped_column(
        SAEnum(SuggestionCategory, name="suggestion_category", create_constraint=True),
        default=SuggestionCategory.GENERAL,
        nullable=False,
    )
    severity: Mapped[SuggestionSeverity] = mapped_column(
        SAEnum(SuggestionSeverity, name="suggestion_severity", create_constraint=True),
        default=SuggestionSeverity.INFO,
        nullable=False,
    )
    
    design_version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    project_id: Mapped[int] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    # Suggestion Status (Step 2)
    status: Mapped[SuggestionStatus] = mapped_column(
        SAEnum(SuggestionStatus, name="suggestion_status", create_constraint=True),
        default=SuggestionStatus.OPEN,
        nullable=False,
    )
    addressed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    addressed_in_version: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    # Keywords that triggered this suggestion (PostgreSQL ARRAY)
    trigger_keywords: Mapped[List[str]] = mapped_column(
        ARRAY(String(100)),
        default=list,
        nullable=False,
    )
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    
    # Relationship
    project: Mapped["Project"] = relationship(
        "Project",
        back_populates="suggestions",
        lazy="selectin",
    )
    
    def __repr__(self) -> str:
        return f"<Suggestion(id={self.id}, title={self.title[:30]}, status={self.status})>"
